# Generated by Django 2.1 on 2018-11-19 05:13

import dendrogram.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=dendrogram.models.profiles_path)),
            ],
        ),
        migrations.CreateModel(
            name='Dendrogram',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dendrogram.Batch')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('png_file', models.FileField(upload_to=dendrogram.models.dendrograms_png_path)),
                ('pdf_file', models.FileField(upload_to=dendrogram.models.dendrograms_pdf_path)),
                ('svg_file', models.FileField(upload_to=dendrogram.models.dendrograms_svg_path)),
                ('emf_file', models.FileField(upload_to=dendrogram.models.dendrograms_emf_path)),
                ('newick_file', models.FileField(upload_to=dendrogram.models.dendrograms_newick_path)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='batch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dendrogram.Batch'),
        ),
    ]
