version: "3"
services:

  postgres:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: benga
    volumes:
      - ./test/data/pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:4.0.5-xenial
    restart: always
    volumes:
      - ./test/data/mongodata:/data/db

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    restart: always
    env_file: envs/rabbitmq.env
    ports:
      - "15672:15672"

  celery:
    image: a504082002/benga:celery
    environment:
      SECRET_KEY: ${SECRET_KEY}
    env_file: envs/web.env
    command: bash -c "python3 manage.py migrate; celery -A benga worker -l info"
    depends_on:
      - rabbitmq
      - postgres

  web:
    image: a504082002/benga:dev
    environment:
      SECRET_KEY: ${SECRET_KEY}
    env_file: envs/web.env
    command: bash -c "python3 manage.py makemigrations; python3 manage.py migrate; python3 manage.py test"
    depends_on:
      - postgres
      - mongo
      - rabbitmq
    ports:
      - "8000:8000"
