version: "3"
services:

  postgres:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - /home/a504082002/Projects/Benga/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo:
    image: mongo:4.0.5-xenial
    restart: always
    volumes:
      - /home/a504082002/Projects/Benga/mongodata:/data/db
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    restart: always
    env_file: envs/rabbitmq.env
    ports:
      - "5672:5672"
      - "15672:15672"

  celery:
    image: a504082002/benga:celery
    env_file: envs/web.env
    command: bash -c "python manage.py makemigrations; python3 manage.py migrate; export CELERY_BROKER_URL='amqp://celery:password123@192.168.30.240:5672/my_vhost'; celery -A benga worker -l info"
    depends_on:
      - rabbitmq
      - postgres

  web:
    image: a504082002/benga:dev
    env_file: envs/web.env
    command: bash -c "python3 manage.py makemigrations; python3 manage.py migrate; bash run.sh"
    depends_on:
      - postgres
      - mongo
      - rabbitmq
    ports:
      - "8000:8000"
