# Generated by Django 2.1 on 2018-11-19 05:13

from django.db import migrations, models
import django.db.models.deletion
import profiling.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=profiling.models.sequences_path)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profiling.Batch')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=profiling.models.profiles_path)),
                ('occurrence', models.SmallIntegerField()),
                ('database', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='sequence',
            name='batch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.Batch'),
        ),
    ]
